objc: true
output: docs
framework_root: ZeroDark.cloud
sdk: iphonesimulator
umbrella_header: ZeroDark.cloud/ZeroDarkCloudUmbrella.h
theme: fullwidth
author: 4th-A Technologies
custom_categories:
- name: Core
  children:
  - ZeroDarkCloud
  - ZeroDarkCloudDelegate
  - ZDCCryptoFile
  - ZDCData
  - ZDCTreesystemPath
- name: Managers
  children:
  - ZDCCloudPathManager
  - ZDCDatabaseManager
  - ZDCDatabaseKeyManager
  - ZDCDirectoryManager
  - ZDCDiskManager
  - ZDCDownloadManager
  - ZDCImageManager
  - ZDCLocalUserManager
  - ZDCNodeManager
  - ZDCProgressManager
  - ZDCPullManager
  - ZDCPushManager
  - ZDCRestManager
  - ZDCSyncManager
  - ZDCUITools
  - ZDCUserManager
  - ZDCUserSearchManager
- name: Model
  children:
  - ZDCBlockchainProof
  - ZDCCloudDataInfo
  - ZDCLocalUser
  - ZDCLocalUserAuth
  - ZDCNode
  - ZDCNodeAnchor
  - ZDCPublicKey
  - ZDCShareItem
  - ZDCShareList
  - ZDCSymmetricKey
  - ZDCTrunkNode
  - ZDCUser
  - ZDCUserIdentity
- name: Billing
  children:
  - ZDCUserBill
  - ZDCUserBillMetadata
  - ZDCAppBill
  - ZDCStorageBill
  - ZDCAppCost
  - ZDCAppCostDetails
- name: File & Streams
  children:
  - ZDCInputStream
  - ZDCInterruptingInputStream
  - CacheFile2CleartextInputStream
  - Cleartext2CacheFileInputStream
  - Cleartext2CloudFileInputStream
  - CloudFile2CleartextInputStream
  - ZDCFileReader
  - ZDCFileChecksum
  - ZDCFileChecksumInstruction
  - ZDCFileConversion
  - ZDCFilesystemMonitor
  - ZDCCacheFileHeader
  - ZDCCloudFileHeader
- name: ZDCCloud
  children:
  - ZDCCloud
  - ZDCCloudConnection
  - ZDCCloudTransaction
  - ZDCCloudOperation
  - ZDCCloudLocator
  - ZDCCloudPath
  - ZDCCloudRcrd
  - ZDCDropboxInvite
  - ZDCGraftInvite
- name: Utilities
  children:
  - BIP39Mnemonic
  - ZDCProgress
  - ZDCAsyncCompletionDispatch
- name: AWS Utilities
  children:
  - AWSDate
  - AWSPayload
  - AWSRegions
  - AWSRegion
  - AWSServices
  - AWSService
  - AWSSignature
exclude:
- /*/Internal/*
