source 'https://github.com/CocoaPods/Specs.git'

workspace 'ZeroDarkCloudTesting'
project 'ZeroDarkCloudTesting.xcodeproj'

use_frameworks!
inhibit_all_warnings!

# Workaround for Xcode bug:
# - https://www.ralfebert.de/ios/blog/cocoapods-clean-input-output-files/
# - https://github.com/CocoaPods/CocoaPods/issues/8073
# - https://github.com/CocoaPods/CocoaPods/pull/8105
# 
install! 'cocoapods', :disable_input_output_paths => true


abstract_target 'both' do
	
	pod 'ZeroDarkCloud', path: '../../', :inhibit_warnings => false
	
	abstract_target 'macOS' do
		platform :osx, '10.12'

		target :'zdc_macOS' do
		end
		
		target :'zdc_macOS_test' do
		end
	end

	abstract_target 'iOS' do
		platform :ios, '10.0'
		
		target :'zdc_iOS' do
		end

		target :'zdc_iOS_test' do
		end
	end
end

