source 'https://github.com/CocoaPods/Specs.git'

workspace 'ZeroDarkTodo'
project 'ZeroDarkTodo.xcodeproj'

use_frameworks!
inhibit_all_warnings!

# Workaround for Xcode bug:
# - https://www.ralfebert.de/ios/blog/cocoapods-clean-input-output-files/
# - https://github.com/CocoaPods/CocoaPods/issues/8073
# - https://github.com/CocoaPods/CocoaPods/pull/8105
# 
install! 'cocoapods', :disable_input_output_paths => true


abstract_target 'ios' do
	platform :ios, '10.1'
		
	# This is the pod you need.
	# In this project we're using it as a "Development Pod".
	# But in your project you'll install it normally like this:
	#
	# pod 'ZeroDarkCloud/Swift'
	#
	pod 'ZeroDarkCloud/Swift', path: '../../', :inhibit_warnings => false
	
	# It's also recommended (but not required) that you use this Pod too.
	# It helps with merging changes and handling conflicts.
	# 
	pod 'ZDCSyncable'
    

	# Used by sample application (not required for your application)
	pod 'CocoaLumberjack/Swift'
	pod 'KGHitTestingViews'
	pod 'SWRevealViewController'
	pod 'ImageScrollView'

	target :'ZeroDarkTodo' do
	end

end
