source 'https://github.com/CocoaPods/Specs.git'

workspace 'KeyTesting'
project 'KeyTesting'
use_frameworks!
inhibit_all_warnings!

# Workaround for Xcode bug:
# - https://www.ralfebert.de/ios/blog/cocoapods-clean-input-output-files/
# - https://github.com/CocoaPods/CocoaPods/issues/8073
# - https://github.com/CocoaPods/CocoaPods/pull/8105
#
install! 'cocoapods', :disable_input_output_paths => true



abstract_target 'ios' do
platform :ios, '10.1'
#pod 'YapDatabase/SQLCipher', :git =>'https://github.com/yapstudios/YapDatabase.git', :commit=>'5a7e70a2101ba78b1f92bc992b78dc2e06adb941'
pod 'YapDatabase/SQLCipher'
pod 'ZeroDarkCloud/Swift', path: '../../', :inhibit_warnings => false

pod 'KGHitTestingViews'

target :'KeyTesting' do
end

end
